# Generated by Django 4.0 on 2022-01-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rent_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='product',
        ),
        migrations.AddField(
            model_name='rent',
            name='product',
            field=models.ManyToManyField(to='app.Product'),
        ),
    ]
