# Generated by Django 4.0 on 2022-01-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_rent_rental_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
