# Generated by Django 4.0 on 2022-01-11 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rent_is_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
